version: "3"
services:
  mysql-db:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=tpachato
      - MYSQL_USER=root
    volumes:
      - db:/var/lib/mysql

  spring_app:
    image: karim369/achat:latest
    container_name: achatspring
    restart: unless-stopped
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysql-db:3306/tpachato?createDatabaseIfNotExist=true&useSSL=false",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "root",
        "spring.datasource.driver-class-name" : "com.mysql.jdbc.Driver",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update",
        "server.servlet.context-path" : "/SpringMVC",
        "server.port" : "8089"
      }'
    ports:
      - 8089:8089
    depends_on:
      - mysql-db
volumes:
  db:


